// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Host": {
        "en": "homee-ID / Hostname / IP",
        "de": "home-ID / Hostname / IP",
        "ru": "homee-ID / имя хоста / IP-",
        "pt": "homee-ID / Hostname / IP",
        "nl": "homee-ID / hostnaam / IP",
        "fr": "homee-ID / Nom d'hôte / IP",
        "it": "homee-ID / Nome host / IP",
        "es": "homee-ID / Nombre de host / IP",
        "pl": "homee-ID / nazwa hosta / adres IP"
    },
    "User": {
        "en": "Username",
        "de": "Nutzername",
        "ru": "имя пользователя",
        "pt": "Nome de usuário",
        "nl": "Gebruikersnaam",
        "fr": "Nom d'utilisateur",
        "it": "Nome utente",
        "es": "Nombre de usuario",
        "pl": "Nazwa Użytkownika"
    },
    "Password": {
        "en": "Password",
        "de": "Passwort",
        "ru": "пароль",
        "pt": "Senha",
        "nl": "Wachtwoord",
        "fr": "Mot de passe",
        "it": "Parola d'ordine",
        "es": "Contraseña",
        "pl": "Hasło"
    }
};
